# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbbdac7bb65512aa4b72a8ed1492e42c175cb9de76a8f6bc66f7f739008be877a22c69c3ce9f32513909788ae16e01f6fda89cd69b50b011dad6440cc54bf65c

test:
  secret_key_base: 7d82733d61b791effb5faa54eb47f83b6c8ff528e343a8e9677d9dd896dd810ee97540eb42060f3ed18f416864a3f81d75dab8ddbc3518a24d394522ec5c81a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
